/* empty css                      */import{a as E,S as x,i as l}from"./assets/vendor-D0cagnvz.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const y="48662828-d5228b65b3bd2a50381de04cd",I="https://pixabay.com/api/";async function g(t,o){return(await E.get(I,{params:{key:y,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40,page:o}})).data.hits}async function B(t){const o=`https://pixabay.com/api/?key=${y}&q=${encodeURIComponent(t)}&image_type=photo`;try{return(await(await fetch(o)).json()).totalHits}catch(s){throw console.error("Ошибка запроса:",s),s}}function h(t){const o=document.querySelector(".gallery"),s=t.map(({webformatURL:n,largeImageURL:e,tags:r,likes:a,views:w,comments:L,downloads:v,totalhits:A})=>`<a href="${e}" class="gallery-item">
                    <img src="${n}" alt="${r}">
                    <div class="info">
                        <p class="text">Likes<br> <span>${a}</span></p>
                        <p class="text">Views<br> <span>${w}</span></p>
                        <p class="text">Comments<br> <span>${L}</span></p>
                        <p class="text">Downloads<br> <span>${v}</span></p>                        
                    </div>
                </a>`).join("");o.insertAdjacentHTML("beforeend",s)}const $=document.getElementById("search-form"),q=document.getElementById("search-input"),S=document.querySelector(".gallery"),m=document.getElementById("loader"),d=document.querySelector(".butn-footer");let b=new x(".gallery a"),i=0,H=40,f,c;function O(){document.getElementById("loader").classList.add("show")}function u(){document.getElementById("loader").classList.remove("show")}u();$.addEventListener("submit",async t=>{if(i=0,c=q.value.trim(),p(),t.preventDefault(),!c){l.warning({title:"Увага",message:"Будь ласка, введіть пошуковий запит!"});return}S.innerHTML="",O();try{const o=await g(c);if(o.length===0){l.info({title:"Немає результатів",message:"Спробуйте інший пошуковий запит!"});return}p(),u(),h(o),b.refresh(),d.style.display="block",d.disabled=!1}catch{m.style.display="none",l.error({title:"Помилка",message:"Щось пішло не так! Спробуйте ще раз."})}finally{m.style.display="none"}});u();const P=document.getElementById("search-forms-two");P.addEventListener("submit",async t=>{t.preventDefault(),p();const o=await g(c,i);h(o),window.scrollBy({top:window.innerHeight-100,behavior:"smooth"}),b.refresh()});async function p(){try{const t=await B(c);_(t)}catch(t){console.error("Ошибка при получении данных:",t)}}function _(t){if(f=Math.ceil(t/H),i+=1,f<i)return d.style.display="none",i=0,l.error({position:"bottomCenter",message:"We're sorry, there are no more posts to load"})}
//# sourceMappingURL=index.js.map
